---
- name: Restart Redis
  service:
    name: redis
    state: restarted

- name: Restart MySQL
  service:
    name: mysqld
    state: restarted

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded

- name: Reload Supervisord
  service:
    name: supervisord
    state: reloaded

- name: Restart MongoDB
  service:
    name: mongod
    state: restarted
