---
- name: Configure RabbitMQ
  template:
    src: rabbitmq.config.j2
    dest: /etc/rabbitmq/rabbitmq.config
    mode: 0644
    owner: root
    group: root
  notify:
  - Restart RabbitMQ

- name: Start RabbitMQ
  service:
    name: rabbitmq-server
    state: started
    enabled: true
