---
- name: Install MySQL repo
  yum:
    name: "{{ mysql_repo_url }}"
    state: present

- name: Disable MySQL 5.6 in repo and enable 5.7
  command: "{{ item }}"
  with_items:
    - yum-config-manager --disable mysql56-community
    - yum-config-manager --enable mysql57-community-dmr
