---
- name: Create new password for root user
  command: "mysqladmin -u root password {{ mysql_root_password }}"

- name: Remove anonymous users
  mysql_user:
    name: ""
    host_all: yes
    state: absent
    login_host: localhost
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Remove the test database
  mysql_db:
    name: test
    state: absent
    login_host: localhost
    login_user: root
    login_password: "{{ mysql_root_password }}"
