---
- name: Create list of Nginx server configs to remove
  set_fact:
    nginx_server_configs_remove:
      - "{{ nginx_server_config_dir }}/default.conf"
      - "{{ nginx_server_config_dir }}/php-fpm.conf"
      - "{{ nginx_server_config_dir }}/php-fpm.conf-7.0"
      - "{{ nginx_server_config_dir }}/ssl.conf"
      - "{{ nginx_server_config_dir }}/virtual.conf"
  when: nginx_server_config_dir is defined

- name: Remove Nginx server configs added by the PHP-FPM install
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ nginx_server_configs_remove | default([]) }}"
  notify:
    - Reload Nginx
