---
- name: "Provision Node.js etc."
  hosts: default
  become: yes
  become_method: sudo
  gather_facts: yes
  force_handlers: true
  any_errors_fatal: true

  roles:
    - common
    - curl
    - iptables
    - nodejs
    - npm
    - nginx
    - supervisord
    - redis
    - mysql
    - mongodb
    - rabbitmq

  handlers:
    - import_tasks: handlers/handlers.yml
