---
- name: Install Redis
  yum:
    name: redis
    state: present

- name: Configure Redis
  template:
    src: redis.conf.j2
    dest: /etc/redis.conf
    mode: 0640
    owner: redis
    group: root
  notify:
  - Restart Redis

- name: Start Redis
  service:
    name: redis
    state: started
    enabled: true
